### PR TITLE
test(Alert): migrate to rtl

### PR DESCRIPTION
**Pull request by illiteratewriter**
- [ ] Bug fix 
- [ ] New feature 
- [x] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by illiteratewriter** [comment]
Is it possible to mock `Transition` for just two tests and leave it as is for the remaining tests? The rest of the tests will pass if you remove the mock, but we need to mock Transition for the other two tests.

**Comment by davidacevedo** [comment]
> Is it possible to mock `Transition` for just two tests and leave it as is for the remaining tests? The rest of the tests will pass if you remove the mock, but we need to mock Transition for the other two tests.

```
diff --git a/src/__tests__/Alert.spec.js b/src/__tests__/Alert.spec.js
index 5dee2ee..fcc77dc 100644
--- a/src/__tests__/Alert.spec.js
+++ b/src/__tests__/Alert.spec.js
@@ -7,18 +7,10 @@ import { Transition } from 'react-transition-group';
 import { testForCustomClass, testForCustomTag } from '../testUtils';
 import { Alert } from '..';
 
-jest.mock('react-transition-group', () => {
-  return {
-    Transition: jest.fn(() => null)
-  }
-})
-
-afterEach(() => {
-  jest.clearAllMocks();
-});
-
-
 describe('Alert', () => {
+  beforeEach(() => {
+    jest.resetModules();
+  })
   // it('should render children', () => {
   //   render(<Alert>Yo!</Alert>);
   //   expect(screen.getByText('Yo!')).toBeInTheDocument();
@@ -112,7 +104,23 @@ describe('Alert', () => {
   //   expect(screen.getByLabelText('oseclay')).toBeInTheDocument();
   // });
 
+  describe('mocking Transition', () => {
+    beforeEach(() => {
+      // eslint-disable-next-line global-require, prefer-destructuring
+
+    })
+  })
   it('should have default transitionTimeouts', () => {
+    jest.doMock('react-transition-group', () => ({
+      Transition: jest.fn(() => null)
+    }))
+
+
+    // eslint-disable-next-line global-require
+    const { Transition } = require('react-transition-group');
+    // eslint-disable-next-line global-require
+    const {Alert} = require('..');
+
     render(<Alert>Yo!</Alert>);
 
     expect(Transition).toHaveBeenCalledWith(expect.objectContaining({
@@ -124,6 +132,15 @@ describe('Alert', () => {
   });
 
   it('should have support configurable transitionTimeouts', () => {
+    jest.doMock('react-transition-group', () => ({
+      Transition: jest.fn(() => null)
+    }))
+
+    // eslint-disable-next-line global-require
+    const { Transition } = require('react-transition-group');
+    // eslint-disable-next-line global-require
+    const {Alert} = require('..');
+
     render(
```

**Comment by illiteratewriter** [comment]
@davidacevedo Thanks a lot. I had tried that but was missing `const { Alert } = require('..');` Now the test is passing. Why is it that we have to require `Alert` again even though it is already in scope?

**Comment by davidacevedo** [comment]
> @davidacevedo Thanks a lot. I had tried that but was missing `const { Alert } = require('..');` Now the test is passing. Why is it that we have to require `Alert` again even though it is already in scope?

Been a bit busy so will be slow to check this stuff out. We have to require because we are stubbing the whole import file versus a piece. Although typing this I feel like we don't need to do all this and can just:
```
import * as TransitionGroup from 'react-transition-group';

// And mock the value of
TransitionGroup.Transition
```

In sinon this would look like:
```
sinon.stub(TransitionGroup, 'Transition').returns('something')
```
I don't know the jest equivalent

**Review by aaronmars — APPROVED** [review]

**Pull request merged**
