### PR TITLE
move to external react-transition-group dependency

### PR DESCRIPTION
**Pull request by ened**
Per https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html:

> react-addons-css-transition-group - Use react-transition-group/CSSTransitionGroup instead. Version 1.1.1 provides a drop-in replacement.

Please review the webpack.base.config.js changes whether it needs changes.

### CODE REVIEW

**Comment by ened** [comment]
Would love to know if anyone is using that patch already?

**Comment by nathancahill** [comment]
Yes, I tested it, but I use Rollup, so I can't speak for the Webpack changes. It works fine otherwise. Would love to see this merged soon, currently a blocker for upgrading to latest React.

**Comment by ened** [comment]
@eddywashere Hi there, could you please give us an update? Thank you

**Comment by samrod** [comment]
Please merge this PR ASAP. The deprecated dependencies are no longer installing and it's breaking our app.

Thanks,

**Comment by TheSharpieOne** [comment]
@samrod that is not how deprecations work.

**Comment by shredd** [comment]
Any status updates regarding this PR?

**Comment by ened** [comment]
.oO( time to fork )

**Comment by balloob** [comment]
This PR messed up the Rollup config, bumping the file size from 95kB to 335kB. Reported the issue as #472.

I have opened a PR with a fix in #474.

**Pull request merged**
