### PR TITLE
feat(FormGrid): Add form-row

### PR DESCRIPTION
**Pull request by Ashniu123**
- [ ] Bug fix 
- [x] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- - [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Modify <Row /> to have an additional prop `form` type `bool` which
adds class "form-row" instead of "row" when enabled.

Closes issue #1195

### CODE REVIEW

**Comment by Ashniu123** [comment]
Any idea why the build is failing? Worker information shows that build was terminated. Can we start it again? I am sure it works.

**Comment by TheSharpieOne** [comment]
No idea why the build is failing. The tests and all LGTM from the source code so I am not too concerned with the build's status.

Thanks for the PR!

**Comment by marcoromag** [comment]
Hi, the typescript part fails with` <Row form></Row>` because the 'form' is already defined in the `interface AllHTMLAttributes<T>` as string.
Not sure if this shall be posted here....

**Comment by Ashniu123** [comment]
> Hi, the typescript part fails with`<Row form></Row>` because the 'form' is already defined in the `interface AllHTMLAttributes<T>` as string.
> Not sure if this shall be posted here....

I'll look into it. Open a new issue regarding this.

**Pull request merged**
