### PR TITLE
Feat(Modal): add destroyOnClose functionality

### PR DESCRIPTION
**Pull request by EndiM**
- [ ] Bug fix 
- [x] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- - [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Addresses issues:
#1061, #1115

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
looks good, just one suggestion, can you rename the prop to `unmountOnClose`? I think mounting and unmounting are more understood terms within react.

**Comment by EndiM** [comment]
@TheSharpieOne Great, I think you're right, `unmountOnClose` is more clear what prop is supposed to do. I changed it and pushed new commit.

**Comment by mouerrr** [comment]
when the next version containing this fix will be released?

**Comment by emileber** [comment]
I'm waiting for a release of this as well. I was really confused when I tried using it since the documentation is based on the master branch it seems, and so it documents unavailable features...

**Pull request merged**
