### PR TITLE
fix(Modal): Made focus optional

### PR DESCRIPTION
**Pull request by miguelc1221**
This PR addresses #335.

It seems that the Modal has a default autoFocus which is why any input inside the modal won't be autoFocused. I exposed a `isFocused` prop which defaults to true. This way if a user wants to autofocus an input, he/she can remove the autofocus from the modal first.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
My two cents, isFocused is probably not the best name, something like autoFocus would be better.

**Comment by miguelc1221** [comment]
yea you're right, fixed.

**Comment by oliverasistemas** [comment]
What is the status on this, is it going to be merged?

**Comment by eddywashere** [comment]
need to re-review and will ship it

**Pull request merged**
