### PR TITLE
Carousel implementation

### PR DESCRIPTION
**Pull request by mkalish**
Implementation of the bootstrap 4 carousel for reactstrap

Addresses: #80

### CODE REVIEW

**Comment by mkalish** [comment]
Let me know if you would like to re-open this PR with the commits squashed

**Comment by mkalish** [comment]
@TheSharpieOne 
I've made the small changes, but wanted to confirm the structural changes I was going to make before getting to far down that path.  I had originally gone with something like this if this was you were thinking of?


```
class Example extends Component {
  constructor(props) {
    super(props);
    this.handleNext = this.handleNext.bind(this);
    this.handlePrev = this.handlePrev.bind(this);
    this.handleGotoIndex = this.handleGotoIndex.bind(this);
    this.state = { activeIndex: 0, direction: 'right' };
  }

  handleNext() {
    this.setState({activeIndex: this.state.activeIndex + 1, direction: 'right'});
  }

 handlePrev() {
    this.setState({activeIndex: this.state.activeIndex - 1, direction: 'left'});
  }

  handleGotoIndex(idx) {
    this.setState({activeIndex: idx});
  }

  render() {
    const items = [
      {
        src: 'src1',
        altText: 'Slide 1',
        caption: 'Slide 1'
      },
      {
        src: 'src2',
        altText: 'Slide 2',
        caption: 'Slide 2'
      },
      {
        src: 'src3',
        altText: 'Slide 3',
        caption: 'Slide 3'
      }
    ];

  const carouselItems = items.map((item, idx) => {
      return (<CarouselItem
        direction={direction}
        key={idx}
        {...item}
        cssModule={cssModule}
      />);
    });

   const { activeIndex } = this.state;
    return (
     <Carousel>
       <CarouselIndicators  activeIndex={activeIndex} onClickHandler={this.handleGotoIndex} />
       {items[0]}
       <CarouselControl direction="prev" directionText="Previous" onClickHandler={this.handlePrev} />
       <CarouselControl direction="next" directionText="Next" onClickHandler={this.handleNext} />
     </Carousel>

      <Carousel items={items} />
    );
  }
}
```

I can go back to this approach, but it seemed like that this would force a user to have to implement the wrap functionality themselves, since that needs to be handle in the previous and next functions?

**Comment by TheSharpieOne** [comment]
I would defer to @eddywashere, but we could have them wrap, or the component could do a mod (`%`). We can make the children be the slides/items and count the children to determine the number of items. `this.props.index % numOfChildren`. You can also determine the whole direction thing when the props update, comparing the current index to the next index. This would also help with the slide change direction when the index change by more than just 1/-1. Looks like your `handleGotoIndex` doesn't determine the direction like your `handleNext` and `handlePrev` do

**Comment by mkalish** [comment]
@TheSharpieOne  @eddywashere 
I have an alternative implementation in this PR #412 that has the consumer implement much more of rotation including the wrapping functionality.

**Comment by mkalish** [comment]
Closing this as #412 is the preferred implementation

**Pull request closed without merging**
