### PR TITLE
feat(Popover/Tooltip): Implented usage of react 16.3 RefObject as target

### PR DESCRIPTION
**Pull request by josh-degraw**
- [x] Bug fix 
- [x] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

R.E. issue #1198

This pull request adds support for using React 16.3 `createRef` object as the `target` and `container` props for `Tooltip` and `Popover` components. I have updated the type definitions in [my fork](https://github.com/josh-degraw/DefinitelyTyped/tree/reactstrap-josh-degraw/types/reactstrap) so that those can be updated as well.

I added tests to cover my changes, but testing is definitely _not_ my forte, so if I did something wrong there or I'm missing something, please let me know and I'll fix / update it ASAP.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
I like where this is going, but it points out another issue that probably needs to be solved as well. Currently we only get the target in `componentDidMount`. Chances are `current` will still be `null` when that runs and even if it updates within the ref the target will never update.

We probably need to grab the target every render. This would help with other cases as well. When the target prop changes, it should trigger a rerender and it should target the new target.

We will not be able to determine when `current` changed via an update check as the ref object will never change and never trigger an update by itself even if the `current` property chances within the ref.

**Comment by virgofx** [comment]
Yeah .. i wasn't sure this was going to work originally; however, I like the concept of being able to supply the refs directly -- wasn't sure if react-popper supported it? Either way, we should just make sure we cover all cases in a thorough test suite which would ensure we don't break any existing apps moving forward.

**Comment by josh-degraw** [comment]
@TheSharpieOne I wouldn't worry too much about it being null by`componentDidMount`.

Straight from [the docs](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element):

> React will assign the current property with the DOM element when the component mounts, and assign it back to null when it unmounts. ref updates happen before `componentDidMount` or `componentDidUpdate` lifecycle hooks.

Also, when using the `ref` object I don't think we'll need to worry that much about knowing if `current` changed. React seems to be pretty smart about it. I've made a really simple [tester app](https://github.com/josh-degraw/reactstrap-ref-tester) using a build of my changes just to show that the functionality works. It switches where the `ref` points to after 5 seconds and the tooltip rerenders just fine.

**Comment by ashleydw** [comment]
Is there a PR for the type definitions? The latest types are missing the `TargetElement` from your fork.

https://github.com/josh-degraw/DefinitelyTyped/commit/f1980369c66ab2a199c35a2d8adcfdbd8bfe98c6
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/03041459989ac55f3031e9bef0492482a5575f91

**Pull request merged**
