### PR TITLE
2431 remove margin bottom form group

### PR DESCRIPTION
**Pull request by AJax2012**
- [ ] Bug fix 
- [ ] New feature 
- [x] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

This pull request addresses an something that was brought up in issue #2431  - removing mb-3 from Form Group. I personally don't believe it requires any updates to documentation, but let me know if you'd like to see changes to the docs and if so, what those changes may be. Thank you!

P.S. since this is my second commit, I added my name to the contributors. Hope nobody minds, haha.

### CODE REVIEW

**Comment by illiteratewriter** [comment]
Can we manually add `className="mb-3" to the examples in Forms for them to look better? For example, Floating Labels used to have space between the inputs which is missing now. Same for Form Feedback, Form Grid and so on.

**Comment by AJax2012** [comment]
> Can we manually add `className="mb-3" to the examples in Forms for them to look better?

Definitely. I'll add that to the PR tomorrow.

**Comment by AJax2012** [comment]
@illiteratewriter, I believe I have added mb-3 to pretty much every storybook doc that I believed needed it. If something is missing or there's one you'd prefer removed, let me know.

**Comment by AJax2012** [comment]
As a side-note; I think the package.json needs some attention - I've had to spend about an hour and a half combined trying to figure out how to get tests to run and storybook to run because of a few issues:

1. react-scripts and react-app-rewired versions are incompatible. To fix, I've removed both, then reinstalled together and it seems to work, but I'mnot sure you want to update react-scripts all the way to ^5.0.1... the version that new version of react-app-rewired that gets installed is ^2.2.1.
2. start-storybook `-s` is depreciated (same with build-storybook). Since you already have `staticDirs` in `.storybook/main.js`, you no longer need it and both static flags can be depreciated

**Review by illiteratewriter — APPROVED** [review]

**Comment by illiteratewriter** [comment]
@AJax2012 1. Reactstrap uses yarn, maybe that's why you encountered the problem. Can you try `yarn` instead of `npm i` and share your thoughts?
2. You can go ahead and submit a PR for the same

**Comment by AJax2012** [comment]
I did both. I actually thought it was very odd that the read me said to use npm, but that is what's in the readme. Yarn wasn't better for me though. That was one of the things I tried when making my updates.

**Comment by AJax2012** [comment]
@illiteratewriter thanks for updating this!

**Comment by davidacevedo** [comment]
Hey @AJax2012, I'd recommend not removing `mb-3` and adding another prop like `noMargin` as UIs would change if anyone updates to the later reactstrap with this change.

**Comment by AJax2012** [comment]
I didn't mean to close it... sorry! Guess I'll create a new PR with the updates requested...

**Pull request closed without merging**
