### PR TITLE
replace png images with svg on cards

### PR DESCRIPTION
**Pull request by charisra**
- [ x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x ] There is an open issue which this change addresses
- [ x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x ] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

fixes: 1470

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Not to be picky, but is there any way to not have the border in the SVG through that service?
Also, we might want to consider just adding the files to the project to avoid third-party hosting issues (such as if that site/service is no longer working, similar to the current issue)

**Comment by charisra** [comment]
@TheSharpieOne updated. I removed the border and placed the images on our project.

**Comment by TheSharpieOne** [comment]
Checkout out https://deploy-preview-1621--reactstrap.netlify.com/components/card/ to see it as it would be hosted. It looks like the URLs need to be like `/assets/318x180.svg`

**Comment by charisra** [comment]
@TheSharpieOne Updated

**Comment by TheSharpieOne** [comment]
Thanks 👍

**Pull request merged**
