### PR TITLE
remove react-addons-css-transition-group

### PR DESCRIPTION
**Pull request by Hongbo-Miao**
Fix https://github.com/reactstrap/reactstrap/issues/602

### CODE REVIEW

**Comment by virgofx** [comment]
The DOCS are being rewritten in a separate branch. Just go off of the readme currently, which is already correct.

**Comment by Hongbo-Miao** [comment]
Oh, do you mean **gatsby-docs**, do you want me to switch to that branch for this PR?

**Comment by virgofx** [comment]
Just leave for now.. Eddy knows about this and Evan can merge or close as necessary. No need to do anything ... just saying latest info will be the Readme.

**Comment by Hongbo-Miao** [comment]
Got it!

**Comment by TheSharpieOne** [comment]
I'd merge this but it probably won't see the light of day because we're probably going going to publish the docs before v5 and v5 removes react-transition-group from peerDeps, adding it to deps so users do not need to install it separately.

**Pull request merged**
