### PR TITLE
fix(#2421): fix carousel sliding in wrong direction

### PR DESCRIPTION
**Pull request by rpong**
- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

I updated the Test `should add the appropriate classes when entering right` to reflect the fixed sliding direction.

closes https://github.com/reactstrap/reactstrap/issues/2421

### CODE REVIEW

**Comment by illiteratewriter** [comment]
The test is supposed to run `carousel-item carousel-item-start carousel-item-next` when entering right. The issue with the test is that `context: { direction: 'end' },` is not getting applied to the Carousel context.

**Comment by rpong** [comment]
> The test is supposed to run `carousel-item carousel-item-start carousel-item-next` when entering right. The issue with the test is that `context: { direction: 'end' },` is not getting applied to the Carousel context.

@illiteratewriter , Thank you for checking, do you have any suggestions how we can make that particular test pass while still aligned to this expected sliding behavior?

https://deploy-preview-2606--reactstrap.netlify.app/?path=/docs/components-carousel--carousel

I thought it was going the other way, hence, I updated the test.

**Comment by rpong** [comment]
@illiteratewriter noticed this just now: https://github.com/reactstrap/reactstrap/pull/2604 seems this is a more complete fix but is out of date from base branch. We are hoping it gets merged soon and we will close our PRs for the the bug. Thank you.

**Comment by illiteratewriter** [comment]
@rpong #2604 has been merged to master.

**Pull request closed without merging**
