### PR TITLE
feat(Popper) react-popper migration v1.3

### PR DESCRIPTION
**Pull request by fnpen**
- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [x] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

I've migrated to 1.3.x and fix tests also, but I had problems with old context API.  I make helper to work with it.

Relevant issue: https://github.com/reactstrap/reactstrap/issues/1197

### CODE REVIEW

**Comment by fnpen** [comment]
@virgofx, do you have any news?

**Comment by RVxLab** [comment]
I would really like this to be merged. It's currently breaking with other packages that require react-popper >= 1.0.2

**Comment by dgreensp** [comment]
@fnpen I'm just a random passer-by, but, what problems did you run into, and do you need help trying to solve them?  Or is this ready for review?

**Comment by fnpen** [comment]
> @fnpen I'm just a random passer-by, but, what problems did you run into, and do you need help trying to solve them? Or is this ready for review?

I'm waiting for somebody to review it, like others. But nobody supports this repo :-(
@virgofx is assigned as the reviewer, but he ignores my questions here.

**Comment by TheSharpieOne** [comment]
This was updated in #1427

**Pull request closed without merging**
