### PR TITLE
Disable popper when inNavbar

### PR DESCRIPTION
**Pull request by supergibbs**
For https://github.com/reactstrap/reactstrap/issues/637

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Tests are needed for the new/different path the code can take when the prop is `true`. Also, sadly the docs do not have an example of a dropdown in a navbar (maybe one can be added?)

**Comment by supergibbs** [comment]
I agree but I am a little lost on how to check that popper isn't used when the prop is set. I can't figure out how to access the style attribute (to ensure it's null) in the final rendered. Other suggestions?

Also FYI, on my mac, `brew install watchman` allows me to run the tests locally.

**Comment by supergibbs** [comment]
@TheSharpieOne Do you have any suggestions on how to test this change?

**Comment by TheSharpieOne** [comment]
You should be able to get the [type](https://github.com/airbnb/enzyme/blob/master/docs/api/ReactWrapper/type.md) of the component which is being rendered and check that it isn't Popper

**Comment by supergibbs** [comment]
@TheSharpieOne Good idea, I added a test for `inNavbar` and updated from master. Let me know if there is anything else!

**Pull request merged**
