### PR TITLE
Pass through unused props in Modal

### PR DESCRIPTION
**Pull request by DanielHuisman**
Currently it's not possible to for example change the size (excluding default Bootstrap sizes) of modals. This change allows users to style the modal dialog.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
My 2 cents on this:
There is a size prop. Bootstrap comes with default sizes, you can override these. You can make your own custom sizes. Make a modal-my-size class and make it the size you want then set the size prop to my-size. There isn't really much need for the styles since there is bootstrap css framework  and if you are not using bootstrap then you may want to find another library.

**Comment by DanielHuisman** [comment]
This patch has more than just that specific use case. I think it's important for a library, such as reacststrap, to support both CSS and inline styles. Almost all other components support passing style elements (some through `...otherProps`), so why not support it here?

**Comment by TheSharpieOne** [comment]
So... Apply the other props here as well

**Comment by DanielHuisman** [comment]
Changed it.

**Comment by eddywashere** [comment]
This is a great improvement, thanks @DanielHuisman!

**Comment by eddywashere** [comment]
released in `3.9.5` and  `4.0.0-alpha.5`

**Pull request merged**
