### PR TITLE
fix(#2467): keyboard support for dropdown listbox

### PR DESCRIPTION
**Pull request by illiteratewriter**
- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by aaronmars** [comment]
Is this issue also present when reading `this.context` here?
https://github.com/reactstrap/reactstrap/pull/2584/files#diff-9ee78bc9632271c79f00e1c79ae05005dd6ea11b1353a515e59fe5b8463efba0R341

**Comment by illiteratewriter** [comment]
@aaronmars I didn't get the question

**Comment by aaronmars** [comment]
Sorry, I meant to link to `Dropdown.js`, line 341:
https://github.com/reactstrap/reactstrap/blob/master/src/Dropdown.js#L341

Just wondering if the `context` vs. `props` issue is present there as well.

**Comment by illiteratewriter** [comment]
That context is just to figure out if the Dropdown is wrapped inside an InputGroup. That one will be empty unless you wrap an InputGroup around the Dropdown. That works as expected.

**Comment by aaronmars** [comment]
Thanks for the clarification!

**Review by aaronmars — APPROVED** [review]

**Pull request merged**
