### PR TITLE
fix(issue #1257)- IE forEach error

### PR DESCRIPTION
**Pull request by jeff-nz**
- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

This fix will shim the object array data preventing it to error out on IE and hopefully other browsers.

Fixes issue 1257
https://github.com/reactstrap/reactstrap/issues/1257

In addition I have also found a link tag with a comma that also causes to error out on IE

### CODE REVIEW

**Comment by jeff-nz** [comment]
Feel free to merge the fix whenever you guys ready.

**Comment by TheSharpieOne** [comment]
IE11 supports both `Object.keys` and `Array.prototype.forEach`: https://caniuse.com/#feat=es5

I believe the issue is not with the usage of those functions specifically, but that in a particular case, forEach is used on something that is not an array. It looks like `els` can be an array _or_ a `NodeList`, and a quick glance at https://developer.mozilla.org/en-US/docs/Web/API/NodeList indicates that [IE doesn't support `forEach` on `NodeList`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Browser_compatibility).

It even go into detail with an example:

> Although NodeList is not an Array, it is possible to iterate over it with forEach(). It can also be converted to a real Array using Array.from().
> 
> However, some older browsers have not implemented NodeList.forEach() nor Array.from(). This can be circumvented by using Array.prototype.forEach() [...]

```js
var list = document.querySelectorAll('input[type=checkbox]');
Array.prototype.forEach.call(list, function (checkbox) {
  checkbox.checked = true;
});
```

Probably need to turn https://github.com/reactstrap/reactstrap/blob/0dc2acda96913db56418a880b9ebd807a9c05076/src/utils.js#L275 and https://github.com/reactstrap/reactstrap/blob/0dc2acda96913db56418a880b9ebd807a9c05076/src/utils.js#L281 into

```js
Array.prototype.forEach.call(els, (el) => {
```

**Comment by jeff-nz** [comment]
i see thanks. I'll do that now.

**Comment by jeff-nz** [comment]
Yes, Array.prototype.forEach.call() works but the data we are passing is still causing it to break on IE 11.

Unlike using loadash's foreach 
- it checks and identifies the type of data > rebuilds if necessary > loops through
- using this will also allow the system to support older IE browsers that are commonly used by the banks.

Please let me know what you think. I only see benefits using the lodash foreach but I can go in further cleaning the data before running Array.prototype.forEach.call().

**Comment by jeff-nz** [comment]
Does reactstrap have a list of browser it supports?

**Pull request closed without merging**
