### PR TITLE
Return event to toggle function

### PR DESCRIPTION
**Pull request by SteveByerly**
Return the click event to passed-in toggle function so that state can be updated dynamically. This would allow you to set a property (say href) on the component and update state by the target's attribute.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Ran into this myself, while this change is needed, it is probably a good it enough. The event isnt passed https://github.com/reactstrap/reactstrap/blob/master/src/DropdownToggle.js#L52
My workaround without a code change was to put use onClick on the the dropdown toggle to get to the event.

**Comment by eddywashere** [comment]
I don't think that toggle is always called with an event object. At least the external toggle methods passed in. Programmatically controlling components doesn't require it, but I could see it being useful. If this is critical, or other components don't have this onClick work around, I'd suggest updating the pr to add the support to the other components for consistency.

**Comment by bherila** [comment]
> set a property (say href) on the component

Where would you put the `href` attribute exactly?

**Comment by SteveByerly** [comment]
@eddywashere @TheSharpieOne thanks for looking. I'll update my PR accordingly.

**Comment by eddywashere** [comment]
closing this out. feel free to reopen when needed

**Pull request closed without merging**
