### PR TITLE
Added missing toggle to Accordion

### PR DESCRIPTION
**Pull request by ml054**
Added missing toggle property to accordion. W/o that we have prop types issue:

```
 Failed prop type: The prop `toggle` is marked as required in `Accordion`, but its value is `undefined`.
```

See here: https://github.com/reactstrap/reactstrap/blob/ee18f48da45a367bf879104df76b0eb380207d89/src/Accordion.js#L25

- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [ ] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by davidacevedo — APPROVED** [review]
Thanks for the contribution!

**Comment by ml054** [comment]
PR is still open... :) So if might work if you manually build version with this PR

**Comment by ml054** [comment]
?

**Comment by ml054** [comment]
Woo hoo, looks like it was already merged. When can I expect this in stable release? We are so close to clean console output. Let's make that happen. :)

**Comment by kpull1** [comment]
It's been a year since this problem has been fixed and it's not released yet. Is anybody using the Accordion?

**Pull request merged**
