### PR TITLE
Add prettier

### PR DESCRIPTION
**Pull request by illiteratewriter**
- [ ] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by aaronmars — COMMENTED** [review]
This looks fine to me.
I'm not sure `eslint-plugin-prettier` is really necessary. Without it, we would just need to add another package.json script to run prettier (and `prettier -w`) explicitly. 
It's mentioned in the prettier docs here: https://prettier.io/docs/en/integrating-with-linters.html#notes

**Comment by illiteratewriter** [comment]
The issue when I ran prettier on its own was it was conflicting with ESLint. This caused circular issues like ESLint would do one thing and prettier would do the exact opposite.

**Comment by aaronmars** [comment]
I see. I suppose that just means there are conflicting rules. `eslint-config-prettier` is supposed to disable the eslint rules for the formatting things that prettier handles, but there might be something more esoteric.
Do you have an example?

**Comment by illiteratewriter** [comment]
@davidacevedo can we add `prettier` also to the checks that are run?

**Comment by illiteratewriter** [comment]
@davidacevedo Cool, will raise a PR for that separately.

**Review by davidacevedo — APPROVED** [review]

**Pull request merged**
