### PR TITLE
fix(Tooltip): match BS default values

### PR DESCRIPTION
**Pull request by TheSharpieOne**
Default tooltip hide delay to 0 to match bootstrap
Add animation prop defaults to true to control animation
Add animationDuration prop defaults to 250 to allow animation duration to be overriden
Adjust TetherContent to allow classNames to change and rerender

Closes: #484

Breaks Tooltip: Tooltip's default hide delay is now 0 (previously 250) and now has fade animation with a duration of 250. This was done to better match bootstrap's default. If you like the previous defaults, you can set `delay={hide:0}` and `animation={false}`

Demo: (left: current; right: proposed)
tooltip-animation

### CODE REVIEW

**Comment by ahalimkara** [comment]
@TheSharpieOne that's a great PR, just a small question, is there any particular reason to set animation duration to 250ms as bootstrap's default is[ 150ms](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L226)?

**Comment by TheSharpieOne** [comment]
Their docs didn't mention the duration and I didn't dig. I guess is assumed the 250 hide delay was supposed to be the hide animation duration.

**Comment by Geczy** [comment]
Is this going to be merged?

**Comment by TheSharpieOne** [comment]
It is waiting on review, but also these changes will conflict with changes coming from v5 for bootstrap v4 beta support where tether was swapped out for popper.js

**Comment by TheSharpieOne** [comment]
Closing this as it will cause issues with v5 which will be the next release.

**Pull request closed without merging**
