### PR TITLE
docs(*): update headers to be more semantic

### PR DESCRIPTION
**Pull request by TheSharpieOne**
Try this one more time... this time I'm opening a PR so I can preview the docs site since it works locally, but doesn't appear to work when on github.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
The PR preview seems to have the same issue as when it was merged... 
Looking at the deployment logs I see this over and over again:
>2:37:04 PM:     ERROR in TypeError: Cannot read property 'toLowerCase' of undefined
2:37:04 PM:         at e.renderDOM (main:85:29079)
2:37:04 PM:         at e.render (main:85:28919)
2:37:04 PM:         at e.read (main:85:28594)
2:37:04 PM:         at Object.renderToString (main:85:31565)
2:37:04 PM:         at main:1:1530
2:37:04 PM:         at main:90:1762
2:37:04 PM:         at main:13:18246
2:37:04 PM:         at r (main:12:7025)
2:37:04 PM:         at main:12:7140
2:37:04 PM:         at r (main:89:31054)
2:37:04 PM:     ERROR in TypeError: Cannot read property 'toLowerCase' of undefined
2:37:04 PM:         at e.renderDOM (main:85:29079)
2:37:05 PM:         at e.render (main:85:28919)
2:37:05 PM:         at e.read (main:85:28594)
2:37:05 PM:         at Object.renderToString (main:85:31565)
2:37:05 PM:         at main:1:1530
2:37:05 PM:         at main:90:1762
2:37:05 PM:         at main:13:18246
2:37:05 PM:         at r (main:12:7025)
2:37:05 PM:         at main:12:7140
2:37:05 PM:         at r (main:89:31054)

Not sure what is causing that. Looking for `toLowerCase` in the codebase doesn't reveal much as that code doesn't change... and again, I don't see that locally.

**Comment by TheSharpieOne** [comment]
That stuff hasn't changed and other builds are currently working. 🤷‍♂️

**Comment by gergely-nagy** [comment]
Meme

**Comment by TheSharpieOne** [comment]
It was use of fragments... I'm guessing the SSR deps are so old they don't support that. I just refactored them out instead of updating the deps.

**Comment by gergely-nagy** [comment]
Nice catch! I didn't pay attention to this detail.

**Pull request merged**
