### PR TITLE
Allow dropdown toggle to accept string value

### PR DESCRIPTION
**Pull request by andyseracuse**
- [ ] Bug fix 
- [ x ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [ x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x ] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x ] My change requires a change to [Typescript typings](./types/lib).
  - [ x] I have updated the typings accordingly.
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

my tests for this change throw errors on a type warning.  This means that my tests do not have except blocks, but rather just mount the component with different properties applied and throw if there is a type error.

### CODE REVIEW

**Comment by kyletsang** [comment]
There's an existing PR #1973 with some similar feedback you can look at.  I pinged the author of that PR since it's pretty stale now.

**Comment by andyseracuse** [comment]
Gotcha.  So should I try to implement the listbox property using the drop-down context as is suggested in that PR?

**Comment by kyletsang** [comment]
I'd give it a bit of time to see if that other PR is abandoned.  If nobody responds in like a week, feel free to take over.

**Comment by andyseracuse** [comment]
Gotcha. Will do.  Thanks!

**Comment by andyseracuse** [comment]
no one has responded to this over the last two weeks.  It seems this is abandoned, so I will take over

**Pull request closed without merging**
