### PR TITLE
Fix missing `window` causing NextJS builds to fail

### LINKED ISSUE #1857: reactstrap 8.5.0, next.js window not defined
- components: `not known`
- reactstrap version `#8.5.0`
- react version `#16.13.1`
- bootstrap version `#4.5.0`
- next.js version `#9.4.4`

### What is happening?
This is a next.js project.
It crashes when building or running next dev after updating reacstrap from 8.4.1 to 8.5.0
Unable to "next build" as well

### What should be happening?
The app should be able to build and run in dev mode

### Steps to reproduce issue
Clone the repo https://github.com/wegeberg/reacstrap-test.git
-- or --
Create a next.js app using npx create-next-app
npm install bootstrap reactstrap --save
add an _app.js file to the pages directory with this content:
```
import 'bootstrap/dist/css/bootstrap.min.css';
const MyApp = ({ Component, pageProps }) => {
    return <Component {...pageProps} />;
};
export default MyApp;
```
Add some reactstrap component s to pages/index.js
npm run dev
Go to http://localhost:3000

### Error message in console
ReferenceError: window is not defined
    at ..../node_modules/reactstrap/lib/polyfill.js:4:3
    at Object.<anonymous> (..../node_modules/reactstrap/lib/polyfill.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (..../node_modules/reactstrap/lib/index.js:374:41)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///reactstrap:1:18)

### Code
https://github.com/wegeberg/reacstrap-test.git

### PR DESCRIPTION
**Pull request by justinbrumley**
- [x] Bug fix 
- [ ] New feature 
- [x] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Closes #1857

### CODE REVIEW

**Comment by iamandrewluca** [comment]
@justinbrumley Thanks!

**Comment by iamandrewluca** [comment]
@TheSharpieOne can we have a patch release on this one?

**Comment by viswassaripalli** [comment]
is it released or what is the ETA of the release. its creating an issue on my production build. please reply quick

**Comment by iamandrewluca** [comment]
A quick workaround is to downgrade to previous version.

**Comment by mverderese** [comment]
Thanks for getting the fix out so quickly. I just downgrade to 8.3.2 to fix this issue for now. Can you please post on this thread when 8.5.1 is release with this patch?

**Comment by iamandrewluca** [comment]
Yes

**Comment by mrassili** [comment]
@iamandrewluca thanks for the quick fix, 8.5.1 going to be released any soon?

**Comment by iamandrewluca** [comment]
Thanks @justinbrumley for the fix. I don't have permissions to release a new version. @TheSharpieOne

**Comment by TheSharpieOne** [comment]
@iamandrewluca you should be able to create the release, I sent you an email with more details. I want to make sure you are able to create a release in case I am not. So give it a try with this one and let me know if you have any trouble.

**Comment by iamandrewluca** [comment]
Ok.

**Comment by iamandrewluca** [comment]
Fixed in https://github.com/reactstrap/reactstrap/releases/tag/8.5.1

**Pull request merged**
