### PR TITLE
convert button to use hooks

### PR DESCRIPTION
**Pull request by illiteratewriter**
- [ ] Bug fix 
- [ ] New feature 
- [X] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [X] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [X] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by davidacevedo — DISMISSED** [review]
Looks good 👍

**Comment by TheSharpieOne** [comment]
Would this be considered a breaking change since it would break anyone that might be trying to get the instance of the component via `ref` (not the `innerRef`)

**Comment by illiteratewriter** [comment]
The Button component was using `innerRef` previously also.

**Review by davidacevedo — APPROVED** [review]
👍

**Comment by davidacevedo** [comment]
> Would this be considered a breaking change since it would break anyone that might be trying to get the instance of the component via `ref` (not the `innerRef`)

@TheSharpieOne I'm curious how many people grab and use the instance of the component. It's not something that is documented here, so we should not let that influence whether we should convert or not. I also don't think it's something we should be supporting.

Also, I would assume the button component will most likely not be affected, as someone can just roll their own button if they wanted to call the onClick function from another button!

**Pull request merged**
