### PR TITLE
chore(travis): Update to handle prerelease deploys

### PR DESCRIPTION
**Pull request by phwebi**
- [ ] Bug fix 
- [ ] New feature 
- [x] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Update travis to handle prerelease deploys

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
To be clear, this will "handle" prerelease but not releasing anything? I figured it would release it with, but the `next` tag or something like that. Without it releasing anything, it seems pointless to even tag it in github.

**Comment by phwebi** [comment]
Oh - I actually misread the `npm run build` as `npm publish`.  Where is the npm package actually published?

**Comment by phwebi** [comment]
Github diff looks a bit wonky. This is the new block I added:
```
 - stage: deploy prerelease
      if: tag =~ ^(\d+)\.(\d+)\.(\d+)-(.+)$
      node_js: 12
      before_script: skip
      script: echo "Deploying ..."
      after_script: skip
      after_success: skip
      before_deploy:
      - echo 'Preparing to publish'
      - npm run build
      deploy:
        provider: npm
        tag: next
        email:
          secure: AUw8fn5gmJKKXzSvLs+vUZRz/htXtUAApRCy6SD7EZyQMHiFMfXCXdOIcSCyiOsxlvsh+Wv12qmfKySd3Yi3exeGbuZ/rQcK+i582iVBiBVRru2wcQ5iN9E21zgaRYk8c3lHWGDzorrJfr3dMbhmi4atmvrMg/u/jVLmz5h4Y8pHZeJ24WSl26NJo4WH2ibjOADfwKZmTH4jPMICKXpMvmUJ7K49LPE8MRHJRwSefadwtVcLuHHBqNOmDmUfNF9bEgTm0FnOtwEycsS6y1seB6pTOyidz9N5F5fB1eCyVuc/ev27Bvw6HL+i8anchtgGlGJyW/yL6yxycNfkGWaoJ243GhMbt4PTNwtiksolGvbgJ071yoRVqV/8m8tnTJWyShy16Y96hD2vFKV8lj4Fru3Ad8s0VU40ebslOa1IlzrmxxuUYOhX9Ir1ryHgnf7AEnVwie0p0IbJJY/SqPsa3kIyeoG9RePoruzS+v685GMRM+O7ZN34x4H2UogzWIql9IvpGAUdO5FDP9Ww8BkuLEv4myTZh7x4chqYLKQXoPIBzCzdbO8Hl4t7BYgFB2OLaTdcqPvjeANp7EtDzemCYFtNLuS34HKHQCwKcfr+Ar6/ZDlSKdWu0w7XC5jk0rYrDn97BKnbnNmn77d6ZWr6bzo439pCu91jW6DEyI6iAOM=
        api_key:
          secure: vnNNG+s14Yqnnj/ZjvMnAvsxd+QeLDlfo/iDA0EyHoFIBaSpApYoPzNd2FSZKyI/2kMYdKwUT40DF/qS+NBbhKY2M/HPUqomDny6Lw7XJKI7gTmtA2trlUR/fcHucOjW8PhMqQhB90J8J/RuWK2nS1Y3Mrhwtkbx0ShRl2mnWeysFOfrNywIi3bMDfUVWwQNcnC8c+w09F/S9tZKjjSSzcK9/raEwvZ2iSr2H6HRdlqf7JEl2H6F3k7ltx01FzIzdoTMAYsNENWDZfZUd8vfjmTfbtvVQC6n6uZd28PB1AGdsgy27aeBUe+C28UDlX6p3p6rRsPoLHXYx4hWlGmQvfIyl+vxlSiv8WcOJy2NnXnoJhMeYNmJVEQpBzWlI906z5UCn5+A3E+mPEKXg0jI/uQF5CFguMwwu2vl5N03ZNtD9tdFR0b53N+GCGkOF7jq7SeviR7b3/YmdHi9q5hFEmBXdYFzajxsaqUDYvHtVnjHSW3yT8pnxOvnG7JErg28bTdcYRHc//IVImjktFFsX85ukbGsgAwQAP9oVU0Wz7b0aQ0REnyW2aMroy1JGs8z/voM4aiNfvF6GwrBysWd4AYkalisjkq/LY1G3NDxU9gvPfRIIckgbQcgJ98eSHlG/2i7HqKlSH9Hf2LBAzkhwke3BTaI/hAuq3k0wDIVSY0=
        skip_cleanup: true
        on:
          tags: true
```
I think this should just publish the prerelease package to npm without publishing the docs, unless I'm missing something.

**Review by TheSharpieOne — APPROVED** [review]

**Comment by TheSharpieOne** [comment]
Probably need to merge master into the bootstrap5 branch so it gets this change.

**Pull request merged**
