### PR TITLE
chore(deps): Update react to 16

### PR DESCRIPTION
**Pull request by TheSharpieOne**
Updates the version of react used in the docs as well as in the tests to 16

Some of the tests around transitions are failing. This is a good thing since it has been reported in #607 that animations/transitions are not working in react 16. When #607 is resolved (and the issues for Collapse and Carousal's animation) the tests should be passing.

**I do need help fixing the transition/animation issues in react 16 and thus getting the tests to pass**

### CODE REVIEW

**Comment by jameswomack** [comment]
Should probably be React ^15 || ^ ^16 and not only 16

**Comment by TheSharpieOne** [comment]
@jameswomack The peerDependencies which allows reactstrap to work with various versions of react when itself is installed as a dependency has `^0.14.9 || ^15.3.0 || ^16.0.0`. The devDependencies version which is one npm install when developing is just `^16.0.0` as it cannot be a range and if it was it would pick the latest version within the range to install.

**Comment by jameswomack** [comment]
@TheSharpieOne Makes sense! I misread the PR :)

**Comment by JonatanSalas** [comment]
@TheSharpieOne I have seen that you mention that you need to fix an issue related to animation/transition. I would like to help you with that! Just tell me which test are failing!

**Comment by TheSharpieOne** [comment]
I think the issues have been addressed. The Travis build is failing because is uses yarn and the yarn lock tells it to use react 15 with enzyme react 16 adaptor. I don't really understand why yarn is still a thing, npm 5 addressed a lot of the issue yarn tried to solve. Now it just splits the community and causes issues.

**Comment by JonatanSalas** [comment]
@TheSharpieOne there's a great adoption on yarn, yes, it's true that NPM 5 addresses a lots of issues that yarn tried to solve. In my case, I use it for a project because of the **workspaces feature**. It simplifies a lot when you have a mono repo with multiple packages.

**Comment by JonatanSalas** [comment]
@TheSharpieOne anyway, great to see that you've addressed the issue! 😄

**Pull request merged**
