### PR TITLE
feat(Popper): Add fade support for ToolTip and Popover (#363)

### PR DESCRIPTION
**Pull request by esoh**
- [ ] Bug fix 
- [x] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Hi, this is my first PR. I hope I'm doing everything right! This is to address issue #363.

### Changes in this PR
- default behavior for PopperContent set to fade in and out, toggleable with prop `fade={false}` in Tooltip/Popover
- default hide delay changed from 250 to 0 since now it fades out as consistent with bootstrap
- separated the popperClasses (e.g. `tooltip show`) from any extra classNames as to apply these classes to the ReactPopper child component for display purposes, and the extra classes will be applied to the root Fade component. I was not sure if this is the intended behavior, or if the extra classNames should be applied to ReactPopper instead.
- updated failing TooltipPopoverWrapper isOpen toggle test to account for the 150ms fade animation and added a test with `fade={false}`

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Thank you for tackling this issue. It's something that has been asked for several times in the past but keeps getting overlooked.

I did notice a few things. First, all of the tooltips and popovers always appear as they have placement of bottom, no matter what the placement value is (See https://deploy-preview-1364--reactstrap.netlify.com/components/tooltips/#Tooltips-List for example)
Also, with `autohide={false}` on the tooltip, it should allow the tooltip to be remain visible while hovering over the tooltip (to select the text or something). While it does do is when moving very fast, once the fade starts, hovering over the tooltip doesn't stop it from fading. I feel as if the fade should stop and the tooltip should stay open (at 100 opacity) in this case, if possible.

**Comment by esoh** [comment]
Thank you for pointing out the issues. I believe I've fixed the ones that you've mentioned, but please let me know if I'm missing anything.

**Comment by TheSharpieOne** [comment]
travis is messed up, closing and reopening to trigger a build

**Comment by AlexanderSribny** [comment]
I have a problem. I've install reactstrap from npm, but there is no changes from this commit. The lastest version of reactstrap is 7.1.0., am I right? So why this changes are not in installation package? Or I maked some mistakes?

**Pull request merged**
