### PR TITLE
forward the React ref

### PR DESCRIPTION
**Pull request by dcousens**
This enables you to
``` js
this.badgeRef = React.createRef()

// ...

<Badge innerRef={this.badgeRef}>A badge</Badge>
<UncontrolledTooltip target={this.badgeRef}>But no badger</UncontrolledTooltip>
```

(https://reactjs.org/docs/forwarding-refs.html)

- [x] Bug fix 
- [x] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dcousens** [comment]
@TheSharpieOne so `innerRef`?

**Comment by TheSharpieOne** [comment]
Yes, please use innerRef.

**Comment by dcousens** [comment]
@TheSharpieOne see 82f4e8f

(will squash when necessary)

**Comment by dcousens** [comment]
Several other components need it to, e.g `Button`

**Pull request merged**
