### PR TITLE
Add support for Toasts (#1346)

### LINKED ISSUE #1346: Add support for Toast messages (Bootstrap 4.2.1)
Please add support for toast messages which were recently added in version 4.2.1:

https://getbootstrap.com/docs/4.2/components/toasts/

### PR DESCRIPTION
**Pull request by seansfkelley**
- [ ] Bug fix 
- [x] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- - [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Supersedes and closes #1384. Fixes #1346.

Note that I didn't rewrite @charlex's commit to adhere to the commit guidelines cause I didn't want to change history and make it look like I wrote that code. Hope that's alright.

### CODE REVIEW

**Comment by seansfkelley** [comment]
Ping @TheSharpieOne, is this good to go or does it need changes?

**Comment by seansfkelley** [comment]
Thanks! :D

**Comment by TheSharpieOne** [comment]
and just released in 8.0.0

**Comment by charlex** [comment]
@seansfkelley Thanks for carrying this over the finish line!

**Pull request merged**
