### PR TITLE
feat(Dropdown): setActiveFromChild prop

### PR DESCRIPTION
**Pull request by FutureKode**
See issue: #960

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
I'm not 100% sure this will work with the use-case in #960. Using react-router's `Link` with it's `activeClassName` means that the `active` prop will not get set, only the "active" class if and when it is active and even that is only evaluated afterwards.
Looking at how react-bootstrap created this feature, they are just matching routes directly in their code to determine if the route is active rather than using anything react-router would give them.
So while this would work, it would not be able to leverage react-router to determine if the link is active, leaving it up to the user to add that logic in the `active` prop.

**Comment by FutureKode** [comment]
Yes you are right :( it doesn't work when using react-router `Link`

**Comment by TheSharpieOne** [comment]
Still a nice feature. The kinks for the Link integration can be worked out later. For now, people can manage the active state of the dropdown via the items's active props rather than having additional logic in their code.

**Comment by apaatsio** [comment]
There's zero documentation for `setActiveFromChild`. It would be nice to always update the documentation when new features are added.

**Comment by apaatsio** [comment]
I don't think the property name is enough documentation in this case. A simple usage example would be clarifying enough, though.

**Comment by FutureKode** [comment]
@apaatsio good idea. I have created a [PR](https://github.com/reactstrap/reactstrap/pull/1014), let me know if it is okay :)

**Pull request merged**
