### PR TITLE
#601 Modal bugs on react ^16

### PR DESCRIPTION
**Pull request by martindavid**
- Add `ReactDOM.unstable_createPortal` to support Fiber version.
- Keep `ReactDOM.unstable_renderSubtreeIntoContainer` as a fallback for < 16 version.

Issue: https://github.com/reactstrap/reactstrap/issues/601

### CODE REVIEW

**Comment by martindavid** [comment]
#601

**Comment by TheSharpieOne** [comment]
I thought I had commented on this earlier, but I apparently did not. The portal API is supposed to be used in the render AFAIK. This means that the logic would be similar, but separated. The render would return null for react <16 and would return the unstable_createPortal for react 16+. Similarly and separately, the opposite would happen in the renderIntoSubtree method; unstable_renderSubtreeIntoContainer would be called for react <15 and nothing would happen for react 16+.

**Comment by kinke** [comment]
Thanks @martindavid, I can confirm that this fixes the `autoFocus` issue for Modals with React 16 (e.g., escape key closing the modal etc.) and the fade-out animation as well.

> The portal API is supposed to be used in the render AFAIK.

@TheSharpieOne: The changes you propose would require more logic changes; `renderIntoSubtree()` is called in 3 places (show(), hide(), componentDidUpdate()).

**Comment by fantua** [comment]
@TheSharpieOne when this and #763 can be released? We have some troubles according to this issues.

**Pull request closed without merging**
