### PR TITLE
add justified attribute for ButtonGroup component

### PR DESCRIPTION
**Pull request by ened**
We should have a sweep one day to add all missing attributes. Perhaps with the BS beta.

### CODE REVIEW

**Comment by ssteinerx** [comment]
Test is failing due to missing props validation:

`26:5  error  'justified' is missing in props validation  react/prop-types`

**Comment by TheSharpieOne** [comment]
`.btn-group-justified` was removed for BS v4. The migration guide says so as well as it is not present in any of the docs nor code when searching. 
https://github.com/twbs/bootstrap/blob/6cf1a106d4fcd043f47d3eab4ffef3eaf868ce38/docs/4.0/migration.md

**Comment by TheSharpieOne** [comment]
I am closing this as `.btn-group-justified` doesn't exist in bootstrap 4.

**Comment by ened** [comment]
Ok. I shall look for a alternative solution then. We needed those justified. :)

**Pull request closed without merging**
