### PR TITLE
Fix import/export not getting transpiled in lib dir

### PR DESCRIPTION
**Pull request by balloob**
Rollup conversion introduced a bug where Babel wouldn't transpile import/export to CommonJS syntax in the lib dir. This PR fixes it.

Report: https://github.com/reactstrap/reactstrap/pull/359#issuecomment-290928268

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
I would also point main in the package.json to the lib index.js as this would allow for better source maps and such.

**Comment by balloob** [comment]
Nah, the source maps are already off since some transpilation happens. Instead I have added source maps back to the UMD output in https://github.com/reactstrap/reactstrap/pull/386

**Comment by balloob** [comment]
Another issue with the lib dir is that if you import from it, you will also have to add the dependencies of Reactstrap to your own `package.json` (ie `reactstrap-tether`).

**Comment by TheSharpieOne** [comment]
You shouldn't need to, reactstrap-tether is a dependency, not a peer or devDep. It will be downloaded when reactstrap is installed and  things know how to resolve it.

**Comment by balloob** [comment]
@TheSharpieOne ah yes, you're right.

**Pull request merged**
