### PR TITLE
fix:(issue#1255-unmounted-uncontrolledtooltip)

### PR DESCRIPTION
**Pull request by jeff-nz**
- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

This fixes the issue on:
https://github.com/reactstrap/reactstrap/issues/1255
```
Error message in console
warning.js:33 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in UncontrolledTooltip (created by [redacted])
[redacted]
printWarning @ warning.js:33
warning @ warning.js:57
warnAboutUpdateOnUnmounted @ react-dom.development.js:11186
scheduleWorkImpl @ react-dom.development.js:12130
scheduleWork @ react-dom.development.js:12082
enqueueSetState @ react-dom.development.js:6644
Component.setState @ react.development.js:238
toggle @ reactstrap.es.js:5337
toggle @ reactstrap.es.js:4180
hide @ reactstrap.es.js:4123
setTimeout (async)
onMouseLeaveTooltip @ reactstrap.es.js:4077
```

### CODE REVIEW

**Comment by jeff-nz** [comment]
Hi @TheSharpieOne ,

The Tooltip component does not set or use any state of its own. This component is only passing props.

However, UncontrolledTooltip has its own state which is causing the issue reported.

Regards,
Jeff

**Comment by TheSharpieOne** [comment]
Tooltip is what triggers the toggle callback. This problem originates within `Tooltip`, `Tooltip` should not be triggering the toggle function if it is unmounted.

**Comment by jeff-nz** [comment]
It's before calling the toggle function is triggered. The error is about setting state on component that is unmounted

Error message that looked like:

```
Error message in console
warning.js:33 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in UncontrolledTooltip (created by [redacted])
[redacted]
printWarning @ warning.js:33
warning @ warning.js:57
warnAboutUpdateOnUnmounted @ react-dom.development.js:11186
scheduleWorkImpl @ react-dom.development.js:12130
scheduleWork @ react-dom.development.js:12082
enqueueSetState @ react-dom.development.js:6644
Component.setState @ react.development.js:238
toggle @ reactstrap.es.js:5337
toggle @ reactstrap.es.js:4180
hide @ reactstrap.es.js:4123
setTimeout (async)
onMouseLeaveTooltip @ reactstrap.es.js:4077

```

**Comment by jeff-nz** [comment]
Here's a link on a similar issue to this:
https://stackoverflow.com/questions/50428842/cant-call-setstate-or-forceupdate-on-an-unmounted-component

**Comment by jeff-nz** [comment]
I hope the additional resource help. The issue is before re-rendering the Tooltip Component.

**Comment by jeff-nz** [comment]
I found an article from the react site that talks about an issue similar to this one and the solution. This issue is a bit complicated, I hope the article can help.

Here's the link:
https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

**Comment by jeff-nz** [comment]
Feel free to merge whenever you are ready.

**Comment by TheSharpieOne** [comment]
I am closing this in favor of canceling the timeouts when the Tooltip unmounts.

**Comment by amillward** [comment]
> I am closing this in favor of canceling the timeouts when the Tooltip unmounts.

Did that fix happen? I still get the error reported in https://github.com/reactstrap/reactstrap/issues/1255

**Pull request closed without merging**
