### PR TITLE
fix(Modal): handle init modal in SSR

### PR DESCRIPTION
**Pull request by lamhieu-vk**
- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

In server-side rendering, Modal will call init but in this time not found `document` and it's will breaks.

### CODE REVIEW

**Comment by virgofx** [comment]
Changes look good. @lamhieu-vk Is everything working as expected in your environment?

**Comment by lamhieu-vk** [comment]
@virgofx Sorry, I forget change title to `WIP`. I will mention to you after done!

**Comment by virgofx** [comment]
No problem. Just let me know if everything is working in your environment as expected as I have not tested personally

**Comment by lamhieu-vk** [comment]
@virgofx I updated PR, I tested in my app and use `next.js` to SSR.

**Comment by virgofx** [comment]
Thanks. Looks good

/cc @TheSharpieOne

**Comment by TheSharpieOne** [comment]
@virgofx you can squash and merge 😉

**Comment by virgofx** [comment]
Just wanted you to look at it :)

**Comment by lamhieu-vk** [comment]
Many thanks for @virgofx @TheSharpieOne

**Comment by justingrant** [comment]
BTW, this PR will also fix #1323.

**Comment by justingrant** [comment]
@lamhieu-vk - Does your PR break auto-focus behavior?  The implementation of `componentDidMount` checks `this.state.isOpen` but your PR moved the initialization of `state.isOpen` into a `setState` call in `componentDidMount`. Because `setState` runs asynchronously (at least in browser React, although I'm not sure about SSR), `state.isOpen` will always be false when `componentDidMount` runs, so the auto-focus check `if (this.state.isOpen && this.props.autoFocus)` will never be true.

Shouldn't that condition be changed to use `this.props` instead of `this.state`?  Like this: 

```javascript
  componentDidMount() {
    if (this.props.isOpen) {
      this.init();
      this.setState({ isOpen: true })
    }

    if (this.props.onEnter) {
      this.props.onEnter();
    }

    // currently:  if (this.state.isOpen && this.props.autoFocus) {
    if (this.props.isOpen && this.props.autoFocus) {
      this.setFocus();
    }

    this._isMounted = true;
  }
```

**Comment by lamhieu-vk** [comment]
@justingrant I think your comment is true, and it's a break in this case. I will update it soon.

**Pull request merged**
