### PR TITLE
fix: Prevent popover/tooltip rendering if target not resolved

### LINKED ISSUE #2058: Tooltip error with ref target in 8.8.0
- components: `Tooltip`
- reactstrap version `#8.8.0`
- import method `es` 
- react version `#17.0.1`
- bootstrap version `#4`

### What is happening?

When `ref` is passed to the Tooltip component, it displays a warning:
```
Warning: Failed prop type: The prop `target` is marked as required in `PopperContent`, but its value is `undefined`.
```

### How to reproduce

```javascript
import React, { useRef } from 'react';
import { UncontrolledTooltip } from 'reactstrap';

const tooltipRef = useRef();

<i ref={tooltipRef} />                                                           
<UncontrolledTooltip  target={tooltipRef}>                      
  Example tooltip       
</UncontrolledTooltip> 
```

### PR DESCRIPTION
**Pull request by kyletsang**
Fixes #2058

- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by willvlad** [comment]
I've just run into the same issue, but I don't think the above fix will solve it. The error looks like it might be caused by wrong use of an array, when the target is just a string: https://github.com/reactstrap/reactstrap/issues/1686

The target IS being passed, but the error is triggered by it not being an array

**Comment by kyletsang** [comment]
@willvlad, are you seeing this exact message or something else?
`Warning: Failed prop type: The prop `target` is marked as required in `PopperContent`, but its value is `undefined`.`

The issue is passing `undefined` to `PopperContent` which is used internally for popovers and tooltips.

The bug is a regression from #2041.  In previous versions, if the popover/tooltip is not open, `PopperContent` is not rendered.  There is a function `updateTarget` that resolves the correct target prop based on the target prop you pass into the popover or tooltip, but this didn't get called yet prior to rendering `PopperContent` and this is what is causing the error. 

The fix here guards against that because if we have no target yet, there's no point rendering `PopperContent`.  `updateTarget` will get called in `componentDidMount` and `render` when the popover or tooltip is opened.

**Comment by willvlad** [comment]
The message I see is "Failed prop type: The prop `target` is marked as required in `PopperContent`, but its value is `undefined`." even though the target is being passed

**Comment by kyletsang** [comment]
Ok, should be the same bug.  Target is passed to tooltip, but internally, it passes something else to PopperContent, so it's nothing wrong with your code.

Anyways, I've released 8.8.1 that should fix this.  Give it some time to propagate to npm.

**Comment by willvlad** [comment]
Thanks, confirm that 8.8.1 fixed it for me!

**Pull request merged**
