### PR TITLE
fix: treeshaking

### LINKED ISSUE #2427: Tree shaking not working in version 9?
- reactstrap version `9.0.1`
- react version `17.0.2`
- bootstrap version `5.1.3`

### What is happening?

Full bundle seems to be included at all times.

Compare: https://bundlephobia.com/package/reactstrap@9.0.1 - Exports Analysis shows everything at the same size
As opposed to: https://bundlephobia.com/package/reactstrap@8.10.1 - Exports Analysis shows different sizes.

### What should be happening?

Unused components should be removed.

### PR DESCRIPTION
**Pull request by illiteratewriter**
- fix #2427 
- migrate from microbundle to babel

- [x] Bug fix 
- [ ] New feature 
- [x] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by shtbik — APPROVED** [review]

**Comment by davidacevedo** [comment]
Hey, can you test this by using something like yarn link or npm link? 

Other than that it looks good

**Comment by illiteratewriter** [comment]
@davidacevedo tested.

**Review by davidacevedo — APPROVED** [review]
Looks good to me 👍

**Comment by adarsh-drishya** [comment]
has it been released yet?

**Comment by anoop0567** [comment]
@adarsh-drishya is there any update on this?

**Comment by adarsh-drishya** [comment]
No mate

**Comment by illiteratewriter** [comment]
This has been released. But there was a bug in this. The issue should be fixed with the next release.

**Comment by adarsh-drishya** [comment]
So is this fixed now? @illiteratewriter

**Comment by illiteratewriter** [comment]
@adarsh-drishya https://bundlephobia.com/package/reactstrap@9.2.0 should be. :)

**Pull request merged**
