### PR TITLE
Bootstrap 4 carousel

### PR DESCRIPTION
**Pull request by mkalish**
Implementation of the bootstrap 4 carousel

Addresses #80

### CODE REVIEW

**Comment by mkalish** [comment]
@TheSharpieOne @eddywashere 
Any thoughts?  I'd love to get this into the next release

**Comment by mkalish** [comment]
@CarlLogan 
I'm done with the work I wanted (I had to use it on a project at work as well).  I just updated the branch so that the linting changes in master get pulled in, so hopefully this can get merged soon.

**Comment by mkalish** [comment]
@eddywashere 
I've updated this branch with the recent updates from master so all the checks are now passing

**Comment by eddywashere** [comment]
Thanks for the ping and updates. I'll check this out this weekend.

**Comment by slimeygecko** [comment]
any chance this can be merged in soon?

**Comment by mkalish** [comment]
@eddywashere Any chance we can get this looked at and merged in soon?

**Comment by mpowell90** [comment]
Please make this happen! Carousel component will be a weapon in the reactstrap arsenal.

**Comment by mkalish** [comment]
@TheSharpieOne 
Did you have any comments here before we could get this merged?

**Comment by mkalish** [comment]
@eddywashere Any chance we can get this merged soon?

**Comment by TheSharpieOne** [comment]
One thing that is missing, but is not a showstopper is `keyboard` prop. It is a boolean which defaults to `true` and controls whether the carousel should react to keyboard events.
This component would just call the `next` and `previous` callbacks.
Also, previous is not defined in the Carousel propTypes.

**Comment by mkalish** [comment]
@TheSharpieOne 
Added a keyboard property

**Pull request merged**
