### PR TITLE
Adding MDBReact To Themes Premium List

### PR DESCRIPTION
**Pull request by bwsky-a**
- [ ] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [ ] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bwsky-a** [comment]
@phwebi Any feedback on this PR or possibly when would it be merged?

**Review by phwebi — APPROVED** [review]

**Comment by bwsky-a** [comment]
@phwebi Do you know why I can't see my changes made on the website? They should probably be visible here - https://reactstrap.github.io/premium-themes/, but unfortunately, I can't see anything

**Comment by bwsky-a** [comment]
@phwebi Do you know why I can't see my changes made on the website?

**Comment by bwsky-a** [comment]
@phwebi any updates?

**Comment by TheSharpieOne** [comment]
The docs only get updated when a new version is published. This is to keep the docs in "lock-step" with the latest release, which is needed to ensure what you see in the docs can be used. Previously we would publish the docs with every change (which would reflect `master`), but we would get feedback that `x` feature found in the docs doesn't work since that feature was not released (and was only in `master`).

Ideally, extra pages, such as premium themes, would be able to be published independently. That and/or we could have all of the docs for multiple, specific versions published at the same time (similar to how you can see older versions of bootstrap on bootstrap's docs site).

**Comment by TheSharpieOne** [comment]
@bwsky-a I just manually updated the docs premium themes

**Pull request merged**
