### PR TITLE
Issue #673 - Clicking on backdrop really fast throwing error.

### PR DESCRIPTION
**Pull request by mwq27**

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
This was already addressed in a yet to be released change. Hoping to release the next version soon, but I am currently having some rollup build issues and cannot generate the release assets.

**Comment by mwq27** [comment]
Ahhh ok cool. I'll take a look at the issues and see if there's something else I might be able to help with.

**Comment by TheSharpieOne** [comment]
just FYI: the rollup issue I am seeing happens on the current master when running `npm run build`, any help is appreciated. (I should probably open an issue to track it, but I was hoping to just fix the issue quickly enough to make the ticket pointless)

**Comment by mwq27** [comment]
Ok cool i'll take a look.

**Comment by mwq27** [comment]
Try this out in the rollup.config @TheSharpieOne 
```js
plugins: [
      nodeResolve(),
      commonjs({
        include: 'node_modules/**'
      }),
      babel({
        plugins: ['external-helpers'],
      }),
    ],
```

With this change I was able to run `npm run build` successfully.

**Comment by TheSharpieOne** [comment]
@mwq27 Awesome! that worked! Thanks a ton! I really need to learn more about rollup and the rollup ecosystem/plugins

**Pull request closed without merging**
