### PR TITLE
feat(*): add way to get ref to focuable components

### PR DESCRIPTION
**Pull request by TheSharpieOne**
The main use-case for refs is the ability to set focus on an element, because of this, I have added the ability to get a ref to components which generate focusable items (inputs, buttons, links/anchor).

I just want to note, using a ref to get an input's value is not the correct way. Using a callback, such `onChange` or `onBlur`, you can use the supplied event to get the value without needing a ref.

### CODE REVIEW

**Comment by eddywashere** [comment]
Could you add lodash noop as the default prop.

**Comment by TheSharpieOne** [comment]
They default to `undefined` and when `undefined` is passed to `ref`, it is the same as not having a `ref` prop which I'd argue is probably better than triggering an extra function (even if the function does nothing).

**Comment by ajainarayanan** [comment]
@TheSharpieOne I agree that refs could be used to set focus on an input element but wouldn't it be more straight forward by accepting a focus(or autoFocus) attribute for focus alone? We could also have a getRef attribute that will return the underlying input element's ref and can be used independently. 

Its more of getting the element ref and focusing it vs setting the attribute of element and make itself focus.

**Comment by eddywashere** [comment]
@TheSharpieOne great point.  I didn't think about that. 👍 

@ajainarayanan good discussion, moving this to #172 since it's out of scope for this pr.

**Pull request merged**
